# version: '2.0'
name: 'lara-ecommerce'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        WWWGUID: '${WWWGUID:-1000}'
    image: laravel-5.7/php-7.4
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    user: 1000:1000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      WWWUSER: '${WWWUSER:-1000}'
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network-laravel
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app-network-laravel
    depends_on:
      - app

  # Postgres
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: testedevweb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - app-network-laravel

# Docker Networks
networks:
  app-network-laravel:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
