zend_extension=xdebug

; Habilita o modo de depuração
xdebug.mode=debug,develop,coverage

; Tenta iniciar a depuração para cada requisição. Ótimo para desenvolvimento.
xdebug.start_with_request=yes

; Onde a sua IDE está escutando. 'host.docker.internal' é um DNS especial
; que aponta do contêiner para a sua máquina host.
xdebug.client_host=host.docker.internal

; (Opcional) Se você quiser que o Xdebug não se conecte automaticamente,
xdebug.discover_client_host=true

; Porta padrão do Xdebug 3. Verifique se sua IDE está escutando nesta porta.
xdebug.client_port=9003

; (Opcional, mas MUITO útil para depurar) Cria um log de conexão do Xdebug.
; Se algo der errado, este arquivo dirá o porquê.
xdebug.log=/tmp/xdebug.log
